apiVersion: v1
kind: Namespace
metadata:
  name: curl-test-ns-a
  labels:
    name: curl-test-ns-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-test-a
  namespace: curl-test-ns-a
  labels:
    app: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-test-a
  template:
    metadata:
      labels:
        app: curl-test-a
    spec:
      containers:
      - name: curl
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: curl-test-svc-a
  namespace: curl-test-ns-a
spec:
  selector:
    app: curl-a
  ports:
  - protocol: TCP
    port: 8080
